// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO
  COMMENTS (
    "id",
    "comment",
    "author_id",
    "post_id",
    "parent_comment_id",
    "created_at"
  )
VALUES
  ($1, $2, $3, $4, $5, $6)
RETURNING
  id, comment, author_id, post_id, parent_comment_id, up_voted, down_voted, created_at
`

type CreateCommentParams struct {
	ID              pgtype.UUID      `json:"id"`
	Comment         string           `json:"comment"`
	AuthorID        pgtype.UUID      `json:"author_id"`
	PostID          pgtype.UUID      `json:"post_id"`
	ParentCommentID pgtype.UUID      `json:"parent_comment_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.Comment,
		arg.AuthorID,
		arg.PostID,
		arg.ParentCommentID,
		arg.CreatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.AuthorID,
		&i.PostID,
		&i.ParentCommentID,
		&i.UpVoted,
		&i.DownVoted,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentsReplies = `-- name: GetCommentsReplies :many
SELECT
  pc.id, pc.comment, pc.author_id, pc.post_id, pc.parent_comment_id, pc.up_voted, pc.down_voted, pc.created_at,
  u.email AS author_email,
  u.name AS author_name,
  u.image AS author_image
FROM
  (
    SELECT
      id, comment, author_id, post_id, parent_comment_id, up_voted, down_voted, created_at
    FROM
      COMMENTS c
    WHERE
      c.post_id = $1
      AND c.parent_comment_id = $2
    ORDER BY
      c.created_at DESC
    LIMIT
      $3
    OFFSET
      $4
  ) pc
  LEFT JOIN users u ON pc.author_id = u.id
`

type GetCommentsRepliesParams struct {
	PostID          pgtype.UUID `json:"post_id"`
	ParentCommentID pgtype.UUID `json:"parent_comment_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

type GetCommentsRepliesRow struct {
	ID              pgtype.UUID      `json:"id"`
	Comment         string           `json:"comment"`
	AuthorID        pgtype.UUID      `json:"author_id"`
	PostID          pgtype.UUID      `json:"post_id"`
	ParentCommentID pgtype.UUID      `json:"parent_comment_id"`
	UpVoted         int32            `json:"up_voted"`
	DownVoted       int32            `json:"down_voted"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AuthorEmail     pgtype.Text      `json:"author_email"`
	AuthorName      pgtype.Text      `json:"author_name"`
	AuthorImage     pgtype.Text      `json:"author_image"`
}

func (q *Queries) GetCommentsReplies(ctx context.Context, arg GetCommentsRepliesParams) ([]GetCommentsRepliesRow, error) {
	rows, err := q.db.Query(ctx, getCommentsReplies,
		arg.PostID,
		arg.ParentCommentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentsRepliesRow{}
	for rows.Next() {
		var i GetCommentsRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.AuthorID,
			&i.PostID,
			&i.ParentCommentID,
			&i.UpVoted,
			&i.DownVoted,
			&i.CreatedAt,
			&i.AuthorEmail,
			&i.AuthorName,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostComments = `-- name: GetPostComments :many
SELECT
  pc.id, pc.comment, pc.author_id, pc.post_id, pc.parent_comment_id, pc.up_voted, pc.down_voted, pc.created_at,
  u.email AS author_email,
  u.name AS author_name,
  u.image AS author_image
FROM
  (
    SELECT
      id, comment, author_id, post_id, parent_comment_id, up_voted, down_voted, created_at
    FROM
      COMMENTS c
    WHERE
      c.post_id = $1
      AND c.parent_comment_id IS NULL
    ORDER BY
      c.created_at DESC
    LIMIT
      $2
    OFFSET
      $3
  ) pc
  LEFT JOIN users u ON pc.author_id = u.id
ORDER BY
  pc.created_at DESC
`

type GetPostCommentsParams struct {
	PostID pgtype.UUID `json:"post_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetPostCommentsRow struct {
	ID              pgtype.UUID      `json:"id"`
	Comment         string           `json:"comment"`
	AuthorID        pgtype.UUID      `json:"author_id"`
	PostID          pgtype.UUID      `json:"post_id"`
	ParentCommentID pgtype.UUID      `json:"parent_comment_id"`
	UpVoted         int32            `json:"up_voted"`
	DownVoted       int32            `json:"down_voted"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AuthorEmail     pgtype.Text      `json:"author_email"`
	AuthorName      pgtype.Text      `json:"author_name"`
	AuthorImage     pgtype.Text      `json:"author_image"`
}

func (q *Queries) GetPostComments(ctx context.Context, arg GetPostCommentsParams) ([]GetPostCommentsRow, error) {
	rows, err := q.db.Query(ctx, getPostComments, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostCommentsRow{}
	for rows.Next() {
		var i GetPostCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.AuthorID,
			&i.PostID,
			&i.ParentCommentID,
			&i.UpVoted,
			&i.DownVoted,
			&i.CreatedAt,
			&i.AuthorEmail,
			&i.AuthorName,
			&i.AuthorImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
