// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.NullUUID
	Email        string
	Name         string
	Password     string
	Image        string
	RefreshToken string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
