// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: comment_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Comment_UpVoteComment_FullMethodName          = "/pb.Comment/UpVoteComment"
	Comment_DownVoteComment_FullMethodName        = "/pb.Comment/DownVoteComment"
	Comment_CheckCommentInteracted_FullMethodName = "/pb.Comment/CheckCommentInteracted"
	Comment_ReplyComment_FullMethodName           = "/pb.Comment/ReplyComment"
)

// CommentClient is the client API for Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentClient interface {
	UpVoteComment(ctx context.Context, in *UpVoteCommentRequest, opts ...grpc.CallOption) (*UpVoteCommentResponse, error)
	DownVoteComment(ctx context.Context, in *DownVoteCommentRequest, opts ...grpc.CallOption) (*DownVoteCommentResponse, error)
	CheckCommentInteracted(ctx context.Context, in *CheckCommentInteractedRequest, opts ...grpc.CallOption) (*CheckCommentInteractedResponse, error)
	ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentResponse, error)
}

type commentClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentClient(cc grpc.ClientConnInterface) CommentClient {
	return &commentClient{cc}
}

func (c *commentClient) UpVoteComment(ctx context.Context, in *UpVoteCommentRequest, opts ...grpc.CallOption) (*UpVoteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpVoteCommentResponse)
	err := c.cc.Invoke(ctx, Comment_UpVoteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) DownVoteComment(ctx context.Context, in *DownVoteCommentRequest, opts ...grpc.CallOption) (*DownVoteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownVoteCommentResponse)
	err := c.cc.Invoke(ctx, Comment_DownVoteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) CheckCommentInteracted(ctx context.Context, in *CheckCommentInteractedRequest, opts ...grpc.CallOption) (*CheckCommentInteractedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCommentInteractedResponse)
	err := c.cc.Invoke(ctx, Comment_CheckCommentInteracted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) ReplyComment(ctx context.Context, in *ReplyCommentRequest, opts ...grpc.CallOption) (*ReplyCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyCommentResponse)
	err := c.cc.Invoke(ctx, Comment_ReplyComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServer is the server API for Comment service.
// All implementations must embed UnimplementedCommentServer
// for forward compatibility.
type CommentServer interface {
	UpVoteComment(context.Context, *UpVoteCommentRequest) (*UpVoteCommentResponse, error)
	DownVoteComment(context.Context, *DownVoteCommentRequest) (*DownVoteCommentResponse, error)
	CheckCommentInteracted(context.Context, *CheckCommentInteractedRequest) (*CheckCommentInteractedResponse, error)
	ReplyComment(context.Context, *ReplyCommentRequest) (*ReplyCommentResponse, error)
	mustEmbedUnimplementedCommentServer()
}

// UnimplementedCommentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentServer struct{}

func (UnimplementedCommentServer) UpVoteComment(context.Context, *UpVoteCommentRequest) (*UpVoteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpVoteComment not implemented")
}
func (UnimplementedCommentServer) DownVoteComment(context.Context, *DownVoteCommentRequest) (*DownVoteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownVoteComment not implemented")
}
func (UnimplementedCommentServer) CheckCommentInteracted(context.Context, *CheckCommentInteractedRequest) (*CheckCommentInteractedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCommentInteracted not implemented")
}
func (UnimplementedCommentServer) ReplyComment(context.Context, *ReplyCommentRequest) (*ReplyCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyComment not implemented")
}
func (UnimplementedCommentServer) mustEmbedUnimplementedCommentServer() {}
func (UnimplementedCommentServer) testEmbeddedByValue()                 {}

// UnsafeCommentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServer will
// result in compilation errors.
type UnsafeCommentServer interface {
	mustEmbedUnimplementedCommentServer()
}

func RegisterCommentServer(s grpc.ServiceRegistrar, srv CommentServer) {
	// If the following call pancis, it indicates UnimplementedCommentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Comment_ServiceDesc, srv)
}

func _Comment_UpVoteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpVoteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).UpVoteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_UpVoteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).UpVoteComment(ctx, req.(*UpVoteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_DownVoteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownVoteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).DownVoteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_DownVoteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).DownVoteComment(ctx, req.(*DownVoteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_CheckCommentInteracted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCommentInteractedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CheckCommentInteracted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_CheckCommentInteracted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CheckCommentInteracted(ctx, req.(*CheckCommentInteractedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_ReplyComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ReplyComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_ReplyComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ReplyComment(ctx, req.(*ReplyCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Comment_ServiceDesc is the grpc.ServiceDesc for Comment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Comment",
	HandlerType: (*CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpVoteComment",
			Handler:    _Comment_UpVoteComment_Handler,
		},
		{
			MethodName: "DownVoteComment",
			Handler:    _Comment_DownVoteComment_Handler,
		},
		{
			MethodName: "CheckCommentInteracted",
			Handler:    _Comment_CheckCommentInteracted_Handler,
		},
		{
			MethodName: "ReplyComment",
			Handler:    _Comment_ReplyComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment_service.proto",
}
