// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: game_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Game_SolveSudoku_FullMethodName         = "/pb.Game/SolveSudoku"
	Game_GenerateSudoku_FullMethodName      = "/pb.Game/GenerateSudoku"
	Game_CheckSudokuSolvable_FullMethodName = "/pb.Game/CheckSudokuSolvable"
)

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameClient interface {
	SolveSudoku(ctx context.Context, in *SolveSudokuRequest, opts ...grpc.CallOption) (*SolveSudokuResponse, error)
	GenerateSudoku(ctx context.Context, in *GenerateSudokuRequest, opts ...grpc.CallOption) (*GenerateSudokuResponse, error)
	CheckSudokuSolvable(ctx context.Context, in *CheckSudokuSolvableRequest, opts ...grpc.CallOption) (*CheckSudokuSolvableResponse, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) SolveSudoku(ctx context.Context, in *SolveSudokuRequest, opts ...grpc.CallOption) (*SolveSudokuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveSudokuResponse)
	err := c.cc.Invoke(ctx, Game_SolveSudoku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GenerateSudoku(ctx context.Context, in *GenerateSudokuRequest, opts ...grpc.CallOption) (*GenerateSudokuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateSudokuResponse)
	err := c.cc.Invoke(ctx, Game_GenerateSudoku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) CheckSudokuSolvable(ctx context.Context, in *CheckSudokuSolvableRequest, opts ...grpc.CallOption) (*CheckSudokuSolvableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSudokuSolvableResponse)
	err := c.cc.Invoke(ctx, Game_CheckSudokuSolvable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility.
type GameServer interface {
	SolveSudoku(context.Context, *SolveSudokuRequest) (*SolveSudokuResponse, error)
	GenerateSudoku(context.Context, *GenerateSudokuRequest) (*GenerateSudokuResponse, error)
	CheckSudokuSolvable(context.Context, *CheckSudokuSolvableRequest) (*CheckSudokuSolvableResponse, error)
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServer struct{}

func (UnimplementedGameServer) SolveSudoku(context.Context, *SolveSudokuRequest) (*SolveSudokuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolveSudoku not implemented")
}
func (UnimplementedGameServer) GenerateSudoku(context.Context, *GenerateSudokuRequest) (*GenerateSudokuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSudoku not implemented")
}
func (UnimplementedGameServer) CheckSudokuSolvable(context.Context, *CheckSudokuSolvableRequest) (*CheckSudokuSolvableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSudokuSolvable not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}
func (UnimplementedGameServer) testEmbeddedByValue()              {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	// If the following call pancis, it indicates UnimplementedGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_SolveSudoku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveSudokuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).SolveSudoku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_SolveSudoku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).SolveSudoku(ctx, req.(*SolveSudokuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GenerateSudoku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSudokuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GenerateSudoku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GenerateSudoku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GenerateSudoku(ctx, req.(*GenerateSudokuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_CheckSudokuSolvable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSudokuSolvableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).CheckSudokuSolvable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_CheckSudokuSolvable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).CheckSudokuSolvable(ctx, req.(*CheckSudokuSolvableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolveSudoku",
			Handler:    _Game_SolveSudoku_Handler,
		},
		{
			MethodName: "GenerateSudoku",
			Handler:    _Game_GenerateSudoku_Handler,
		},
		{
			MethodName: "CheckSudokuSolvable",
			Handler:    _Game_CheckSudokuSolvable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_service.proto",
}
